### ISSUE TITLE
Could you provide the question-answer pairs annotation source code ?

### ISSUE THREAD

**Issue by VincentDENGP** [ATR-DBI/ScanQA#13]
Thank you for the interesting work! I wonder could you kindly provide the source code of data labelling tool? I am  currently planing to label more data (More kinds of question and More difficult answer forms) on ScanNet to further study the spatial-relation in 3D-QA tasks.

**Comment by miyatai2** [comment]
Hello,

I apologize, but I am unable to share our code for the labeling tool with you.

However, if you are interested in creating your own 3D visualizer, you can check out resources such as Three.js (https://threejs.org/) or Potree (https://github.com/potree/potree/).

Additionally, one of the authors of ScanRefer has released visualization code, which you can find at https://github.com/daveredrum/ScanRefer_Browser. However, please note that we did not use this code in our project.

I hope this information is helpful to you.
