### ISSUE TITLE
A question about the OracleImage

### ISSUE THREAD

**Issue by 02bbt** [ATR-DBI/ScanQA#3]
Hi, I am wondering how to get the OracleImage that is mentioned in your paper for the training task to make a comparison. I have viewed the Scannet datasets and struggled to find the OracleImage for every task. I want to ask how to get it for the targeted proposal, thank you so much!

**Comment by miyatai2** [comment]
We obtained the oracle images around the target bboxes with open3d.  The script is not released now because we will use it for another unpublished research.

**Comment by 02bbt** [comment]
Thanks for your reply and I'll close this issue later~
