### ISSUE TITLE
The evaluation metrics for image captioning

### ISSUE THREAD

**Issue by yvfengZhong** [ATR-DBI/ScanQA#6]
Hi, I'm interested in the 3D-QA task, and thanks for your paper and code.

Could you tell me how to validate the model by the evaluation metrics for image captioning?

**Comment by miyatai2** [comment]
Hi, 

To address long answers, we used BLEU, CIDEr, and so on in our study.
Check scripts/score.py for information on how to use these evaluation metrics.

**Comment by yvfengZhong** [comment]
Thanks!
