### ISSUE TITLE
Some questions about  the val set and object annotation.

### ISSUE THREAD

**Issue by WaylonZhangW** [ATR-DBI/ScanQA#9]
Hi, thanks for the excellent work! I got some questions about this project. 
1. I noticed that there exist some unanswerable samples in the val set, Since we treat this QA problem as the multi-classification problem, and the answer vocabulary is from the train set. The size of total val set is 4675, but the answerable val set is 4008. And it seems we only evaluate the model on the answerable val set, I try to evaluate on the whole val set, the performance drops from 22 to 19 or so (a rough number). **I'd like to know the situation of the test set.**

``` 
elif split == 'val':
    self.all_data_size = len(scanqa)
    if use_unanswerable:
        self.scanqa = scanqa
    else:
        self.scanqa = [data for data in scanqa if len(set(data['answers']) & set(answer_cands)) > 0]
```
2. I found that there is more than one object annotation in the data, however, you only use the first object annotation, could I know the reason? 
```        
object_name = None if object_names is None else object_names[0]
object_cat = self.raw2label[object_name] if object_name in self.raw2label else 17
```
Hope to get a useful response!

**Comment by WaylonZhangW** [comment]
3. Another Question about test set, there are only "question", "question id", "scene_id " in the ScanQA_v1.0_test_w_obj.json .  I think it should have the object annotation("object_ids" and "object_names"), is that right?

**Comment by miyatai2** [comment]
1. We evaluate models on a test set including unanswerable ones. It's the same way score.py does.

2. We tried multi-label classification for object localization, but QA performance was only slightly improved. Since the main target of this study is QA,  we used the simplified model.

3. ScanQA_v1.0_test_w_obj.json is used for the leaderboard, so it is correct.

**Comment by WaylonZhangW** [comment]
Hi again,
Thanks for your response, it helps me a lot. However, I am still confused about Question 3,  if ScanQA_v1.0_test_w_obj.json does not have object annotation,  the two sorts of test sets are the same, since they only have "question", "question id", "scene_id ". What is the difference between  ScanQA_v1.0_test_w_obj.json and ScanQA_v1.0_test_wo_obj.json?

**Comment by miyatai2** [comment]
> For question 3:

ScanQA_v1.0_test_w_obj.json was created from val in the ScanRefer dataset. So the object_name is known (for us) and we can provide the OracleImage+MCAN results.
ScanQA_v1.0_test_wo_obj.json was created from test in ScanRefer dataset. The object_name is unknown for us.

**Comment by WaylonZhangW** [comment]
thanks for your reply, I see what you're saying. Actually test_w_obj and test_wo_obj are the same for me, because object_name is not released.
